{
  "swagger": "2.0",
  "info": {
    "title": "Quiz API",
    "description": "Quiz API",
    "version": "v1"
  },
  "paths": {
    "/quiz/": {
      "get": {
        "summary": "Returns a list of questions.",
        "description": "Returns a list of questions.",
        "responses": {
          "200": {
            "examples": {
              "application/json" : {
                "id": 1,
                "question": "random question",
                "answer1": "wrong",
                "answer2": "wrong2",
                "answer3": "correct",
                "answer4": "wrongagain",
                "answerindex": 3
              }
            },
            "description": "A JSON array of questions"
          },
          "404":{
            "description": "404 not found"
          }
        }
      },
      "post": {
        "summary": "posts a new question.",
        "description": "Posts a new question.",
        "responses": {
          "200": {
            "examples": {
              "application/json" : {
                "id": 1,
                "question": "random question",
                "answer1": "wrong",
                "answer2": "wrong2",
                "answer3": "correct",
                "answer4": "wrongagain",
                "answerindex": 3
              }
            },
            "description": "A JSON question"
          },
          "404":{
            "description": "404 not found"
          }
        }
      },
      "put": {
        "summary": "update existing question by id.",
        "description": "update existing question by id.",
        "responses": {
          "200": {
            "examples": {
              "application/json" : {
                "id": 1,
                "question": "random question",
                "answer1": "wrong",
                "answer2": "wrong2",
                "answer3": "correct",
                "answer4": "wrongagain",
                "answerindex": 3
              }
            },
            "description": "A JSON question"
          },
          "404":{
            "description": "404 not found"
          }
        }
      }
    },
    "/quiz/delete/{id}": {
      "delete": {
        "summary": "delete existing question by id.",
        "description": "delete existing question by id.",
        "responses": {
          "200": {
            "examples": {
              "application/json" : {
                "id": 1,
                "question": "random question",
                "answer1": "wrong",
                "answer2": "wrong2",
                "answer3": "correct",
                "answer4": "wrongagain",
                "answerindex": 3
              }
            },
            "description": "A JSON question"
          },
          "404":{
            "description": "404 not found"
          }
        }
      }
    },
    "/score/": {
      "post": {
        "summary": "posts a new highscore.",
        "description": "Posts a new highscore.",
        "responses": {
          "200": {
            "examples": {
              "application/json" : {
                "name": "tommy",
                "value": "100"
              }
            },
            "description": "A JSON highscore"
          },
          "404":{
            "description": "404 not found"
          }
        }
      },
      "put": {
        "summary": "updates a highscore by name.",
        "description": "updates a highscore by name.",
        "responses": {
          "200": {
            "examples": {
              "application/json" : {
                "name": "tommy",
                "value": "100"
              }
            },
            "description": "A JSON highscore"
          },
          "404":{
            "description": "404 not found"
          }
        }
      }
    },
    "/score/delete/{id}": {
      "delete": {
        "summary": "deletes a highscore.",
        "description": "deletes a highscore.",
        "responses": {
          "200": {
            "examples": {
              "application/json" : {
                "name": "tommy"
              }
            },
            "description": "A JSON highscore"
          },
          "404":{
            "description": "404 not found"
          }
        }
      }
    },
    "/counter/":{
      "post": {
        "summary": "Increments counter for api calls.",
        "description": "Increments counter for api calls.",
        "responses": {
          "200": {
            "description": "success"
          },
          "404":{
            "description": "404 not found"
          }
        }
      }
    },
    "/login/":{
      "post": {
        "summary": "posts a new login.",
        "description": "posts a new login.",
        "responses": {
          "200": {
            "examples": {
              "application/json" : {
                "username": "id",
                "password": "pass"
              }
            },
            "description": "A users login details"
          },
          "404":{
            "description": "404 not found"
          }
        }
      },
      "put": {
        "summary": "updates an existing login.",
        "description": "updates an existing login.",
        "responses": {
          "200": {
            "examples": {
              "application/json" : {
                "username": "id",
                "password": "pass"
              }
            },
            "description": "A users login details"
          },
          "404":{
            "description": "404 not found"
          }
        }
      }
    }
  },
  "definitions": {
    "Question": {
      "type": "object",
      "properties": {
        "question": {
          "type": "string",
          "format": "VARCHAR(255)"
        },
        "answer1": {
          "type": "string",
          "format": "VARCHAR(255)"
        },
        "answer2": {
          "type": "integer",
          "format": "VARCHAR(255)"
        },
        "answer3": {
          "type": "string",
          "format": "VARCHAR(255)"
        },
        "answer4": {
          "type": "string",
          "format": "VARCHAR(255)"
        },
        "answerIndex": {
          "type": "integer",
          "format": "int"
        }
      }
    },
    "Score": {
      "type": "object",
      "properties": {
        "Name": {
          "type": "string",
          "format": "VARCHAR(255)"
        },
        "Score": {
          "type": "integer",
          "format": "int"
        }
      }
    },
    "Login": {
      "type": "object",
      "properties": {
        "UserName": {
          "type": "string",
          "format": "VARCHAR(255)"
        },
        "Password": {
          "type": "string",
          "format": "VARCHAR(255)"
        }
      }
    }
  }
}
